FROM node:18

# copy base files
COPY package*.json /usr/src/
COPY yarn.lock /usr/src/
COPY tsconfig.json /usr/src/
COPY .eslintrc.json /usr/src/

# copy the common package
RUN mkdir -p /usr/src/common
COPY common/. /usr/src/common/

# prepare client and copy files
RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client
COPY client/. /usr/src/client/

RUN yarn install

EXPOSE 6969

CMD [ "yarn", "start" ]
