version: '3'

services:  
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ${MEDIA_DIRECTORY}:/usr/src/media
      - ./server/src:/usr/src/app/src:ro
  
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile.dev
    ports:
      - "6969:6969"
    depends_on:
      - server
    volumes:
      - ./client/src:/usr/src/app/src:ro
