version: '3'

services:  
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ${MEDIA_DIRECTORY}:/usr/src/media
  
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "6969:6969"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
