version: '3'

services:  
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ${MEDIA_DIRECTORY}:/usr/src/media
  
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "6969:80"
    depends_on:
      - server
